= System-Wide Requirements

== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt I4 Weiterentwicklung der Mitgliederdatenbank des StuRa spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

== Systemweite funktionale Anforderungen
Ausarbeitung eines Datenschutzkonzeptes, welches die Anforderungen jederzeit erfüllt:

F1: Die personenbezogenen Daten sollen vor unberechtigtem Zugriff geschützt sein. +
F2: Persistenz der Daten. Die eingegebenen Werte sollen validiert werden, der Werteberich geprüft werden. 

== Qualitätsanforderungen für das Gesamtsystem
=== Benutzbarkeit (Usability)
Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

U1: Das Mitglied/ Der Admin sollte die Bedienung innerhalb eines Tages erlernen. +
U2: Ausführen einer Hauptfunktionalität darf nicht mehr als 10 Klicks beanspruchen. 

=== Zuverlässigkeit (Reliability)
R1: Datenbank soll einmal die Woche ein Backup machen. Maximal drei Versionen der Datenbank sollen gespeichert werden.

=== Effizienz (Performance)
P1: Die Ladezeiten einer neuen Seite sollte sich auf zwei Sekunden beschränken, unter der Voraussetzung einer 16Mbit/s-Anschlusses. +

=== Wartbarkeit (Supportability)
S1: Das System soll einfach erweiterbar und wartbar sein. 

== Zusätzliche Anforderungen
=== Einschränkungen
* Ressourcenbegrenzungen - Speicherplatzbegrenzung auf 5MB pro Dokument, welches hochgeladen wird.
* Datenbank soll dreimal die Woche ein Backup machen. Maximal drei Versionen der Datenbank sollen gespeichert werden.

=== Rechtliche Anforderungen
* Nutzung von freien Lizenzen (Open Source)