= Ergebnisse (SAd)
// rund 6 Seiten
== Projektergebnisse

Mithilfe unserer fertiggestellten Software ist es nun möglich Kandidaturen zu verwalten. Das schließt Funktionen wie beispielsweise das Anlegen einer neuen Kandidatur, das Bearbeiten und das Löschen ein. Abgesehen davon, können Kandidaten, welche bei einer Wahl gewählt worden sind, problemlos mit nur zwei Mausklicks als Mitglieder aufgenommen werden. +
Rote Ausrufezeichen vor Mitgliedernamen machen den Admin auf unvollständige Profile aufmerksam, die er noch überarbeiten muss. Die eingebauten Checklisten, die für jedes einzelne Mitglied angelegt werden, geben Auskunft darüber, ob die geforderten Dokumente erfolgreich eingepflegt worden sind. +
Des Weiteren sind angemeldete Mitglieder dazu in der Lage, andere Mitglieder direkt per E-Mail zu kontaktieren. Hierzu muss nur auf das Mail-Icon des jeweiligen Mitgliedes geklickt werden und es öffnet sich das vorbereitete Mailprogramm, über das der Kontakt aufgenommen werden kann. +

Die oben beschriebenen Funktionalitäten beziehen sich alle auf umgesetzte Use Cases, welche eine hohe bis mittlere Priorität hatten. Dementsprechend wurden die für die Auftraggeber bedeutsamsten Anforderungen implementiert und unsere Umsetzung jener schon freudig akzeptiert. +

Use Cases mit einer geringen bis sehr geringen Priorität konnten teilweise aus Zeitgründen oder Komplexitätsgründen nicht umgesetzt werden. Gewünscht war unter anderem, dass der Workload der einzelnen Mitglieder erfasst und sich daraus automatisch die Aufwandsentschädigung berechnet. Doch nach einem langen Meeting mit einem der Admins wurde uns das umfangreiche Ausmaß dieser Aufgabe dargelegt und unter Anbetracht der nötigen Zeit, die wir zur Implementation der anderen Use Cases benötigten, haben wir davon abgesehen diesen speziellenUse Case weiter auszuarbeiten und umzusetzen. Die Generierung von druckbaren Stimmzetteln, welche verschiedene Kandidaturen für eine Wahl listen sollten, konnte leider aus zeitlichen Gründen nicht verwirklicht werden.

== Reflexion pro Teammitglied

