= Manuela Ziesche (MZi)

//stolz auf
//was lief gut
//neu gelernt
//besser beim nächsten Mal

Wenn mich in den letzten zwei Semestern jemand gefragt hat, wie Uni läuft, hab ich den Meisten von diesem Projekt erzählt. Ich war sehr stolz, die Projektmanagerin dieses Teams sein zu dürfen und mit netten Leuten ein tolles System zu weiterzuentwickeln. Anfangs wusste ich nicht, ob Projektmanagement überhaupt etwas für mich ist. Aber im Laufe der Zeit habe ich gemerkt, dass mir die Tätigkeiten sehr viel Spaß bereiten. Aus diesem Grund habe ich mich auch für das IT Projektmanagement für mein Praktikum entschieden. 
Ich freue mich, dass ich später die Kenntnisse, welche ich in SE I und II gesammelt habe, weiter anwenden kann. Schon bei meinem Bewerbungsgespräch habe ich festgestellt, dass ich viele Dinge aus dem Projekt und den Vorlesungen erwähnen konnte, was meinen Gegenüber auch sehr gefreut hat.

Ich bin jedoch nicht nur stolz auf meine persönliche Weiterentwicklung, sondern freue mich, dass das Team von SE I4 so gut zusammengewachsen ist. Eigentlich waren unsere Meetings nur für den fachlichen Austausch gedacht, doch im Laufe der Zeit sind wir nach den fachlichen Tagesordnungspunkten immer mehr zu privaten Themen gewechselt. Anfangs waren die Meetings immer etwas stumm. Doch nun, kurz vom Ende bin ich schon traurig, dass die Montags- und Mittwochsmeetings mit dem Team wegfallen. 

Abgesehen von der menschlichen Entwicklung haben wir ein tolles System entwickelt, welches hoffentlich für den StuRa sindvoll einsetzbar ist und den Usern viel Zeit spart. Ich hätte am Anfang des Projektes nicht gedacht, dass ich selber in den StuRa gehe. Doch für unsere Arbeit war dies eine sehr gute Ergänzung und auch so bin ich froh, dass ich durch SE auf den StuRa und dessen Arbeit aufmerksam geworden bin und mich dort einbringen kann. Ich hoffe, dass ich als Mitglied des StuRa nächstes Jahr die Weiterentwicklung der Mitgliederdatenbank betreuen darf und mich dann über neue Ergänzungen an unserem System freuen kann. 

An sich liefen die meisten Sachen echt gut im Projekt. Die Priorisierung der Use Cases hat uns dazu verholfen, die wichtigsten Sachen zuerst anzugehen und somit das System sinnvoll zu erweitern. Natürlich gab es auch Talfahrten in dem Projekt, vor allem in meiner persönlichen Einstellung. Ab und zu gab es Zeiten, in denen ich einfach keine Energie hatte, Arbeit für das Projekt zu machen. Doch die Verpflichtung gegenüber dem Team hat mich dazu gebracht, weiterzumachen und durchzuziehen. Spätestens in den Teammeetings, in welchen wir uns über unsere Erfolge und Probleme austauschen konnten, hatte ich wieder neue Energie geschöpft und Lust meinen Aufgaben nachzugehen.
Die gesamte Teamorganisation lief sehr gut. Wir sind zu guten Teamkollegen zusammengewachsen und hatten ein entspanntes Arbeitsklima, welches natürlich positiv zu dem Erfolg dazu beigetragen hat.

In dem gesamten Projekt habe ich sehr viel Neues dazu gelernt. Erstens, was es heißt sehr gut im Team zu arbeiten. Für Dinge, die wir uns vorgenommen haben, hat sich immer jemand bereit erklärt, diese nach nach bestem Gewissen zu erledigen. Außerdem habe ich den agilen Softwareentwicklungsprozess kennen gelernt.

Dinge, die mir im jetzigen Projekt nicht so gefallen haben und welche ich in einem späteren Projekt definitiv ändern würde, sind es, dass wir eher zu einem so gut funktionierenden Team zusammen wachsen sollten. Bei Software Engineering I waren wir noch nicht so gut eingespielt wie später. Das kann aber auch daran liegen, dass wir uns durch Corona noch nicht einmal gesehen haben. Aus dem gesamten Projekt kannte ich vorher lediglich einen Studienkollegen, da dieser in meinem Kurs ist. Da hätte es mir auch sehr geholfen mehr Durchsetzungskraft zu haben und Abende einzuführen, in denen wir uns besser kennen lernen und einfach nur quatschen. Eine bessere Durchsetzungskraft hätte ich auch für das Problem gebraucht, welches das eine Teammitglied mitgebracht hat, weil er sich dem Team ziemlich doll entzogen hat. Wir sind in der Zeit zu einem guten Team zusammengewachsen, haben ihn jedoch etwas außen vor gelassen. Nächstes Mal würde ich noch öfter versuchen auf ihn zu zugehen und ihn besser zu integrieren. Falls das auch nichts gebracht hätte, wäre es meine Aufgabe gewesen, dem Team öfter klarzumachen, dass wir das Problem offen ansprechen sollen, vor allem beim Herrn Anke.

Zusammenfassend bin ich aber sehr glücklich, dass ich so eine tolle Chance bekommen habe, mich selber weiterzuentwickeln und Praxiserfahrung in dem Modul sammeln zu können.