= Benjamin Müller

Anders als noch in Software Engineering 1, habe ich mittlerweile einige Erfahrungen in die-sem Bereich sammeln können. Da ich nun genauer wusste was auf uns zukommen wird, war der Einstieg auch wesentlich einfacher. In den ersten Teammeetings wurde schon der grobe Fahrplan für unser Projekt in diesem Semester festgelegt, sowie eine Fehleranalyse des vor-herigen Semesters durchgeführt und die Verteilung der Aufgaben besprochen.

==== Weiterführen des Projekts

Während der Fehleranalyse sind uns zunächst die Mängel in unserer Architektur aufgefallen. Zusammen mit der noch unvollständigen Analyse, lag der Fokus nun also darauf, unsere alte Dokumentation zu überarbeiten und zu verbessern. Da ein Kommilitone und ich weiterhin die Rolle des Architekten innehatten, lag es also auch an uns diese Fehler zu beseitigen. Da es uns leider weiterhin fachlich schwer fiel uns in die verschiedenen Architekturmechanis-men hineinzudenken, haben wir Unterstützung durch ein weiteres Teammitglied erhalten. Generell lässt sich sagen, dass die Zusammenarbeit im Team um ein vielfaches besser lief als noch zuvor, da wir uns gegenseitig besser kennengelernt haben.

==== Verlauf des Projektes

Durch die bessere und effizientere Zusammenarbeit, gelang es uns unsere Aufgaben immer besser zu erledigen. Allgemein steigerte dies auch meine Motivation, mit und für das Team zu Arbeiten. Im Laufe des Projektes mussten wir allerdings feststellen, dass ein Teammitglied nicht ganz so motiviert war, um nicht zu sagen gar nicht. Dies führte dazu, dass wir die Aufgaben neu verteilen bzw. anders aufteilen mussten. Auch wenn dadurch vereinzelt die Stimmung gedrückt war, spricht für mich der weitere Verlauf ganz klar dafür, dass es die richtige Entscheidung von uns war. Durch ein klärendes Gespräch war es uns möglich mit den Tests wie geplant zu beginnen und nebenbei die Architektur auf Vordermann zu bringen. Leider haben wir es aber nicht geschafft den richtigen Umgang mit dem zuvor genannten Kommilitonen zu finden, ihn zu motivieren und besser in die Gruppe zu integrieren. Zu sehr stand uns der gute Wille im Weg niemanden ans Messer liefern zu wollen, was schlussendlich dazu führte, dass wir dieses Problem zu spät angesprochen haben. Eine zufriedenstellende Klärung wird deshalb wohl nicht mehr möglich sein.

==== Einschätzung zum aktuellen Stand

Im letzten Semester und auch zu Beginn dieses Semesters hatte ich noch das Gefühl den anderen Teams hinterher zu sein. Doch durch unsere Teamarbeit und das große Engagement meiner Teammitglieder, gelang es uns gut aus unseren Fehlern zu lernen. Selbstverständlich konnten wir keine perfekte Arbeitsweise in diesen zwei Semestern erlernen. Aber nichts desto trotz finde ich, wir haben eine Menge verbessern können. Die wichtigsten Use-Cases konnten komplett ausformuliert, programmiert und getestet werden. Das spiegelte sich auch in den einzelnen Meetings mit unseren Themenstellern wieder, welche während der Vorführung unseres Fortschrittes sehr zufrieden waren. Ich halte es daher nicht für schlimm, das wir nicht alle Use-Cases zu 100% bearbeiten konnten. Da selbst der Themensteller meinte, dass einzelne Use-Cases nicht im Verhältnis stehen was Aufwand und Nutzen betrifft. Daher sehe ich sehr positiv auf unser Projekt und Team und freue mich diese Erfahrung gesammelt zu haben.
