= Bayu Anggi Saputra


Beim ersten Meeting hatte ich ein Problem und konnte mein Mikrofon nicht benutzen, aber die Mitglieder reagierten mit viel Verständnis und von da an wurde mir klar, dass ich im richtigen Team bin, um dieses Projekt zu beginnen und darauf bin ich stolz, solche guten Mitglieder zu haben. 

Die Projektarbeit im Modul Software Engineering war eine sehr interessante Erfahrung, bei der ich natürlich Neues Gelernt habe und  ein unterstützendes Mitglied war. Jeder hat seine eigene Perspektive, was es interessant macht. Ich habe viel aus den bestehenden Problemen gelernt, wie man sie durch Diskussionen löst und vieles mehr. Alles ging schnell, weil es mir sehr gut gefallen hat. Ich bin sehr stolz ein Teil dieses Projektes gewesen zu sein und ein gutes System erstellt zu haben.
 
Dinge, die mir während der Projektarbeit nicht gefielen und sich im nächsten Projekten ändern werden, sind, dass ich die Probleme lieber selber in die Hand nehme anstatt um Hilfe zu fragen. Ich bin auch nicht besonders offen bezüglich den Problemen, weil ich finde, dass ich zuerst alle Aufgaben und meine Probleme bearbeiten muss, erst dann kann ich frei darüber im Meeting sprechen, dies ist wahrscheinlich eine schlechte Charaktereigenschaft meinerseits, die ich zum nächsten Projekt ändern muss, damit dieses noch besser laufen wird. 

Vielen Dank euch allen für die Zeit und weiterhin viel Erfolg bein Studium oder der Arbeit und bleibt gesund.