= Sabine Adam (SAd)

//stolz auf
//was lief gut
//neu gelernt
//besser beim nächsten Mal

Zusammenfassend kann gesagt werden, dass ich sehr zufrieden mit meiner eigenen und der Arbeit von unserem Team bin. Gerade zu Beginn der Gruppenarbeit, welche im Rahmen der Lehrveranstaltungen Software Engineering I/II durchgeführt wurde, konnte ich mir keine so langanhaltende Produktivität vorstellen, wie sie für ein Projekt dieser Art benötigt wird. Doch ich wurde überrascht. Natürlich war das Maß der erbrachten Arbeit nicht immer konstant, doch es gab auch keine großen Abweichungen. Des Weiteren hat mich die vergleichsweise schnell entwickelte Gruppendynamik erstaunt, bedenkt man, dass wir uns zum damaligen Zeitpunkt alle nicht kannten und uns bis heute kein einziges Mal von Angesicht zu Angesicht gesehen haben. Aus diesem Grund bin ich außerordentlich stolz auf unsere gesamte Projektarbeit. Trotz Corona und der damit zusammenhängenden Hindernisse, haben wir es geschafft als Team zu agieren und die gewünschten Anforderungen an die Software umzusetzen.

Die Erarbeitung von Lösungen in der Gruppe lief meiner Meinung nach relativ gut. In den wöchentlichen Meetings hatte man die Gelegenheit, neben kleinen Erfolgen, auch Probleme zu präsentieren, die anschließend durch die "Schwarmintelligenz" gelöst wurden. Ein anderer erwähnenswerter Aspekt stellt die Kommunikation mit den Auftraggebern dar. Im Gespräch mit anderen Gruppen ist uns aufgefallen, dass das in Kontakt kommen mit beispielsweise den Stackholdern nicht immer so unbeschwert ablaufen muss, wie bei uns. Über mehrere Kommunikationswege waren wir zu jeder Zeit in der Lage unsere Auftraggeber zu erreichen (ab und an auch etwas kurzfristiger), wenn wir Fragen hatten oder um etwas vorzuzeigen.

Dieses Projekt hat mir die Wichtigkeit von Dokumentationen vor Augen geführt. Sei es ein Protokoll bei einem Gespräch mit den Auftraggebern oder Tutoren, oder allgemein die Dokumentation rund um die Anwendung. Ein Großteil unserer Iterationen verbrachten wir mit der Analyse der Ausführungen der Vorgängergruppe, da diese sehr umfangreich doch teilweise unübersichtlich war. Abgesehen davon wurde uns das Tool Git/GitHub im Zuge der Versionsverwaltung vorgestellt, welches sich als sehr nützlich erwiesen hat und das ich sicherlich in Zukunft erneut nutzen werde. Weiterhin hat die Vielseitigkeit von Asciidoc sehr zu meiner Arbeit als Architektin, Protokollantin und die als Technical Writer beigetragen.

Rückblickend hätte ich mir mehr Vertrauen in mich selbst gewünscht, um mich mehr um die Rolle als Entwickler zu bemühen. Doch gerade für dieses Projekt fand ich es gut mich in all den anderen Bereichen zu betätigen, die man sonst bei kleineren Einzelprojekten vernachlässigt.

Abschließend möchte ich mich noch allgemein befürwortend für das Projekt an sich aussprechen. Zu Beginn des Moduls habe ich von der Idee einer semesterübergreifenden Gruppenarbeit nicht viel gehalten. Die Teamarbeiten in der Schule empfand ich selten als sinnvoll, interessant oder lehrreich. Doch das galt nicht für dieses Projekt. Neben den fachlichen Praktiken, die wir nach deren Vermittlung direkt anwenden konnten, hat mir der soziale Aspekt besonders gut gefallen. Das Coronasemester hat es erschwert neue Bekanntschaften zu machen und sich mit Freunden auszutauschen. Doch während der Gruppenarbeit wurde, neben emsigen Arbeiten, oft gelacht und interessante Geschichten ausgetauscht. Alles in Allem eine angenehme Atmosphäre in mitten der Zeiten von Corona, die sehr zur mentalen Gesundheit beigetragen hat.