= Leander Vasco Schwarze (LVS)

Die Projektarbeit im Modul Software Engineering war eine sehr interessante Erfahrung, aus der ich einiges gelernt habe. Als Entwickler war ich natürlich derjenige, der sich am meisten mit der Implementation des Systems beschäftigt hat. Dabei habe ich sehr viel gelernt über die Entwicklung mit einem Webframework (Django) und Webentwicklung im Allgemeinen (HTML, CSS, JavaScript), sowie einige Python-Grundlagen. In all diesen Bereichen hatte ich zu Beginn des Projekts kaum bis gar keine Kenntnisse. 
Auch der Ablauf des Deployments einer Webanwendung und welche Schritte dafür nötig sind, war mir zuvor unbekannt. Darüber habe ich ebenfalls etwas gelernt.
Neben meiner Tätigkeit als Entwickler war ich ebenfalls immer wieder Ansprechpartner bei Fragen des Architekten und des Testers, sodass ich auch einige Einblicke in die Bereiche der Architektur und der Qualitätssicherung erhalten konnte.

Insgesamt bin ich sehr stolz, auf das, was wir als Team geschafft haben: Ein System weiterentwickelt, dass später tatsächlich angewendet wird und den Nutzern bei ihrer Arbeit hilft. Zu Beginn des Projektes war ich zunächst etwas skeptisch, ob wir überhaupt viel schaffen werden, da niemand von uns Kenntnisse oder Erfahrungen mit Softwareprojekten dieser Art und Größe oder mit Webanwendungsentwicklung hatte. Außerdem sollten wir ein bestehendes System weiterentwickeln, was einen hohen Einarbeitungsaufwand bedeutete. Aber vor allem gegen Ende des Semesters waren wir alle ziemlich produktiv und haben doch einiges fertiggestellt.
Zudem muss man bedenken, dass wir all dies unter den Bedingungen der Corona-Pandemie geschafft haben. Das bedeutet, dass unsere gesamte Arbeit online stattfand und wir als Team uns nicht einmal persönlich getroffen haben. Daher können wir meiner Meinung nach sehr stolz sein, auf das, was wir geleistet haben.

Mir ist aufgefallen, dass in unserem Team vor allem die Kommunikation bzw. der Austausch untereinander sehr gut funktioniert hat. In den 1-2 Meetings pro Woche wurden Ergebnisse präsentiert und Probleme geklärt und im Laufe des Projektes verstanden wir uns immer besser. Das hat auch dazu geführt, dass die Aufgabenverteilung in unserem Team gut funktioniert hat. Wenn es neue Aufgaben zu erledigen gab, fand sich immer jemand, der diese freiwillig übernahm.

Zu guter Letzt muss man natürlich auch sagen, dass nicht alles perfekt geklappt hat. Ich würde beim nächsten Projekt ein paar Dinge anders machen. Zum Einen würde ich viel früher mit der Entwicklung beginnen. Wir haben erst relativ spät begonnen (ein paar Wochen nach Beginn des 4. Semesters), was dazu geführt hat, dass wir nicht alles geschafft haben, was wir uns vorgenommen hatten und dass vor allem gegen Ende des Semesters mehr Druck vorhanden war (nicht nur für mich als Entwickler sondern auch für unseren Tester). Es wäre besser gewesen, bereits gegen Ende des 3. Semesters mit der Entwicklung zu beginnen, bspw. mit einem kleinen Prototyp, da dies für mehr Motivation im Team sorgt (man sieht Ergebnisse) und man dadurch auch mehr Zeit für die Entwicklung und das Verfassen von Tests hat.
Weiterhin haben wir uns manchmal nicht ganz genau an den Open Unified Process gehalten, sodass wir teilweise (v.a. bzgl. Entwicklung und Tests) ein bisschen wie im Wasserfallmodell gearbeitet haben.

Alles in Allem würde ich aber sagen, dass dieses Projekt sehr erfolgreich war. Ich habe viel gelernt, nicht nur Technisches, sondern auch über die agile Softwareentwicklung, was mir in der Zukunft sicherlich helfen wird. Ich hatte zuvor noch nie in einem Team an einem Softwareprojekt gearbeitet, schon gar nicht an einem Projekt dieser Größe. Daher war dieses Projekt eine sehr wertvolle Erfahrung und ich finde es gut, dass uns Studenten diese Möglichkeit geboten wird, an einem realen Problem zu arbeiten und eine Softwarelösung dazu zu entwickeln.