= Manuela Ziesche (MZi)

//stolz auf
//was lief gut
//neu gelernt
//besser beim nächsten Mal

Rückblickend möchte ich sagen, dass uns dieses Projekt alle weiter bringt. Den einen mehr oder eben weniger, aber wir haben alle viel Wichtiges dazu gelernt. 
Wenn mich Leute gefragt haben, wo ich später mit meinem Studium hin möchte, wusste ich vor Software Engineering I tatsächlich nicht, was ich denen antworten soll. Umso stolzer bin ich, dass ich diesen Menschen heute erzählen kann, dass ich ein Praktikum im IT Projektmanagement machen werde und wenn mir dieser Bereich dann immernoch so gut gefällt, ich mich da später wohl doch sehen kann. All das hat mit dem Projekt in SE angefangen, vorher wusste ich gar nicht, was eine Projektmanagerin ausmacht.

Aber ich bin nicht nur stolz auf meinen mentalen Wachstum/Erfolg, viel glücklicher bin ich zu sehen, was unser Team doch in dieser kurzen, stressigen Zeit erreicht hat. Wir haben das System echt gut weiterentwickelt und das hat nur funktioniert, indem wir im Team gearbeitet haben. Das ist mir bis zu SE auch immer etwas schwieriger gefallen. Ich kann meine Teamfähigkeit sicher immernoch weiterentwickeln, aber der Anfang ist schon einmal gemacht. 

Aus meiner Perspektive lief viel gut. Das Team hat sich supergut zusammengefunden und im zweiten Semester auch echt gut zusammen gearbeitet.  


